### PR TITLE
Renaming a round function for compilation with newer GCC

### LINKED ISSUE #38: Getting error when im trying to compile it
`/bin/sh: 1: svn: not found
/bin/sh: 1: svnversion: not found
g++ -O2   -MMD -MF obj/x86_64/.MSVC_Round.d -MT obj/x86_64/MSVC_Round.o -c -o obj/x86_64/MSVC_Round.o MSVC_Round.cpp
In file included from MSVC_Round.cpp:1:0:
MSVC_Round.h:5:17: error: ‘int round(float)’ conflicts with a previous declaration
 int round (float);
                 ^
In file included from /usr/include/c++/6/math.h:36:0,
                 from MSVC_Round.h:3,
                 from MSVC_Round.cpp:1:
/usr/include/c++/6/cmath:1708:3: note: previous declaration ‘constexpr float std::round(float)’
   round(float __x)
   ^~~~~
Makefile:62: recipe for target 'obj/x86_64/MSVC_Round.o' failed
make: *** [obj/x86_64/MSVC_Round.o] Error 1
sense@Sense:~/Masaüstü/tpc$ 
`

Here im getting the problem when im triyng to compile it with "make" without admin privileges.

### PR DESCRIPTION
**Pull request by MrCsabaToth**
Fixes #38

### CODE REVIEW

**Comment by llimon** [comment]
Looks to be abandoned, This PR still fixes the build in 2024, Tried in Ubuntu and g++ 13.2.0 
```
g++ (Ubuntu 13.2.0-23ubuntu4) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
